
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '66B43EF200A364C123259A44D15B0880'
    
_lr_action_items = {'EXE':([7,],[9,]),'K':([25,26,32,34,],[27,29,35,36,]),'SYSTEM':([7,],[10,]),'Q':([0,27,29,35,36,],[7,31,33,37,38,]),'HEADER':([0,],[1,]),'SESSION':([15,16,],[17,18,]),'COMMA':([25,26,],[28,30,]),'BETWEEN':([9,10,13,14,17,18,21,22,],[11,12,15,16,19,20,23,24,]),'INTEGER':([11,12,19,20,23,24,28,30,],[13,14,21,22,25,26,32,34,]),'$end':([1,2,3,4,5,6,8,31,33,37,38,],[-6,-2,-5,-1,-3,-4,0,-8,-10,-7,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'exe':([0,],[2,]),'systemnc':([0,],[3,]),'header':([0,],[4,]),'exenc':([0,],[5,]),'system':([0,],[6,]),'start':([0,],[8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> header','start',1,'p_start','plywindowstasks.py',47),
  ('start -> exe','start',1,'p_start','plywindowstasks.py',48),
  ('start -> exenc','start',1,'p_start','plywindowstasks.py',49),
  ('start -> system','start',1,'p_start','plywindowstasks.py',50),
  ('start -> systemnc','start',1,'p_start','plywindowstasks.py',51),
  ('header -> HEADER','header',1,'p_header','plywindowstasks.py',55),
  ('exe -> Q EXE BETWEEN INTEGER BETWEEN SESSION BETWEEN INTEGER BETWEEN INTEGER COMMA INTEGER K Q','exe',14,'p_exe','plywindowstasks.py',59),
  ('exenc -> Q EXE BETWEEN INTEGER BETWEEN SESSION BETWEEN INTEGER BETWEEN INTEGER K Q','exenc',12,'p_exenc','plywindowstasks.py',63),
  ('system -> Q SYSTEM BETWEEN INTEGER BETWEEN SESSION BETWEEN INTEGER BETWEEN INTEGER COMMA INTEGER K Q','system',14,'p_system','plywindowstasks.py',67),
  ('systemnc -> Q SYSTEM BETWEEN INTEGER BETWEEN SESSION BETWEEN INTEGER BETWEEN INTEGER K Q','systemnc',12,'p_systemnc','plywindowstasks.py',71),
]
